name: Long Log Message

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Long Log Message
      run: |
        for i in {1..10000}
        do
          echo "This is line $i of the long log message"
        done
